[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
error-stack = "0.5.0"
pollster = "0.4.0"
thiserror = "2.0.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wgpu = "23.0.0"
winit = "0.30.5"
